parameters:
    project_url: https://github.com/schulit/portal

common:
    app:
        url: "%env(APP_URL)%"
        name: "%env(APP_NAME)%"
        version: "%version%"
        project_url: "%project_url%"
        logo: "%env(APP_LOGO)%"
    locales: "%locales%"
    menu: mainMenu