# Full configuration reference available at:
# https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/reference.html
dh_auditor:
    enabled: '%env(bool:AUDIT_ENABLED)%'
    timezone: 'Europe/Berlin'
    providers:
        doctrine:
            viewer: true
            table_prefix: null
            table_suffix: '_audit'
