easy_admin:
    site_name: "%env(APP_NAME)%"
    user:
        display_name: true
        name_property_path: 'username'
    entities:
        Absence:
            class: App\Entity\Absence
            form:
                fields:
                    - { property: date, type: date, type_options: { widget: 'single_text' }}
                    - lessonStart
                    - lessonEnd
                    - teacher
                    - studyGroup

        Exam:
            class: App\Entity\Exam
            form:
                fields:
                    - { property: externalId, required: false }
                    - date
                    - lessonStart
                    - lessonEnd
                    - description
                    - tuitions
                    - students

        Infotext:
            class: App\Entity\Infotext
            form:
                fields:
                    - { property: date, type_options: { widget: 'single_text' } }
                    - content

        Grade:
            class: App\Entity\Grade
            form:
                fields:
                    - { property: externalId, required: false }
                    - name
                    - allowCollapse
                    - students
        GradeTeacher:
            class: App\Entity\GradeTeacher

        GradeMembership:
            class: App\Entity\GradeMembership

        Room:
            class: App\Entity\Room

        Student:
            class: App\Entity\Student
            list:
                fields:
                    - externalId
                    - firstname
                    - lastname
                    - { property: gender, template: 'admin/ea/enum.html.twig' }
                    - email
                    - status
                    - birthday
                    - approvedPrivacyCategories
            form:
                fields:
                    - { property: externalId, required: false }
                    - firstname
                    - lastname
                    - { property: gender, type_options: { translation_domain: enums } }
                    - email
                    - status
                    - { property: birthday, type_options: { widget: 'single_text' } }
                    - approvedPrivacyCategories

        StudyGroup:
            class: App\Entity\StudyGroup
            list:
                fields:
                    - externalId
                    - name
                    - { property: type, template: 'admin/ea/enum.html.twig' }
                    - grades
                    - memberships
                    - tuitions
                    - section
            form:
                fields:
                    - { property: externalId, required: false }
                    - name
                    - { property: type, type_options: { translation_domain: enums } }
                    - grades
                    - tuitions
                    - section

        StudyGroupMembership:
            class: App\Entity\StudyGroupMembership

        Substitution:
            class: App\Entity\Substitution
            form:
                fields:
                    - externalId
                    - { property: date, type_options: { widget: 'single_text' } }
                    - lessonStart
                    - lessonEnd
                    - startsBefore
                    - type
                    - subject
                    - replacementSubject
                    - rooms
                    - replacementRooms
                    - remark
                    - teachers
                    - replacementTeachers
                    - studyGroups
                    - replacementStudyGroups
                    - replacementGrades
                    - { property: updatedAt, type: date, type_options: { widget: 'single_text' }}

        Tuition:
            class: App\Entity\Tuition
            form:
                fields:
                    - externalId
                    - name
                    - displayName
                    - subject
                    - teachers
                    - studyGroup

        TimetableLesson:
            class: App\Entity\TimetableLesson
            form:
                fields:
                    - externalId
                    - period
                    - week
                    - day
                    - lesson
                    - isDoubleLesson
                    - tuition
                    - room
                    - subject
                    - location

        User:
            class: App\Entity\User
            disabled_actions:
                - new
            list:
                fields:
                    - username
                    - firstname
                    - lastname
                    - email
                    - { property: userType, template: 'admin/ea/enum.html.twig' }
                    - teacher
                    - students
                    - { property: idpId, template: 'admin/ea/uuid.html.twig' }
            form:
                fields:
                    - username
                    - firstname
                    - lastname
                    - email
                    - { property: userType, type_options: { translation_domain: enums } }
                    - teacher
                    - students

        FreeTimespan:
            class: App\Entity\FreeTimespan
            form:
                fields:
                    - { property: date, type: date, type_options: { widget: 'single_text' }}
                    - start
                    - end

        SickNote:
            class: App\Entity\SickNote
