nelmio_api_doc:
    documentation:
        info:
            title: "%env(APP_NAME)%"
            version: "%version%"
        securityDefinitions:
            oauth:
                type: oauth2
                flow: accessCode
                authorizationUrl: /oauth2/authorize
                tokenUrl: /oauth2/token
                scopes:
                    - messages
                    - exams
                    - substitutions
                    - timetable
                    - appointments
            apiKey:
                type: apiKey
                in: header
                name: X-Token
        security:
            oauth:
                - messages
                - exams
                - substitutions
                - timetable
                - appointments
            apiKey: []

    areas: # to filter documented areas
        default:
            path_patterns: [^/api/v]

        import:
            path_patterns: [^/api/import]


