nelmio_api_doc:
    documentation:
        info:
            title: "%env(APP_NAME)%"
            version: "%version%"

    areas: # to filter documented areas
        default:
            path_patterns: [^/api/v]

        import:
            path_patterns: [^/api/import]

