# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        messages:
            local:
                directory: '%kernel.root_dir%/files/messages'
        documents:
            local:
                directory: '%kernel.root_dir%/files/documents'
        wiki:
            local:
                directory: '%kernel.root_dir%/files/wiki'

    filesystems:
        messages:
            adapter: messages
        documents:
            adapter: documents
        wiki:
            adapter: wiki
