# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        messages:
            local:
                directory: '%kernel.project_dir%/files/messages'
        documents:
            local:
                directory: '%kernel.project_dir%/files/documents'
        wiki:
            local:
                directory: '%kernel.project_dir%/files/wiki'

        sick_notes:
            local:
                directory: '%kernel.project_dir%/files/sick_notes'

    filesystems:
        messages:
            adapter: messages
            mount: messages
        documents:
            adapter: documents
            mount: documents
        wiki:
            adapter: wiki
            mount: wiki
        sick_notes:
            adapter: sick_notes
            mount: sick_notes
