# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database:
            entity:
                class: App:User
                property: username

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/import, roles: ROLE_IMPORT }

    role_hierarchy:
        ROLE_ADMIN: [ ROLE_USER, ROLE_WIKI_ADMIN, ROLE_DOCUMENTS_ADMIN, ROLE_MESSAGE_ADMIN, ROLE_APPOINTMENTS_ADMIN ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
        ROLE_MESSAGE_CREATOR: ROLE_USER
        ROLE_MESSAGE_ADMIN: [ ROLE_MESSAGE_CREATOR, ROLE_USER ]
        ROLE_WIKI_ADMIN: ROLE_USER
        ROLE_DOCUMENTS_ADMIN: ROLE_USER
        ROLE_APPOINTMENTS_ADMIN: ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        ics:
            pattern: ^/(appointments|timetable|exams)/ics/
            stateless: true
            device: true

        login:
            anonymous: ~
            pattern: ^/saml/(login|discovery)$

        secured:
            pattern: ^/
            light_saml_sp:
                provider: database
                user_creator: App\Security\User\UserCreator
                login_path: /saml/login
                check_path: /saml/login_check
                attribute_mapper: App\Security\User\AttributeMapper
                token_factory: SchoolIT\CommonBundle\Security\Factory\SamlSpTokenFactory
            logout:
                path: /logout
            switch_user: true

        main:
            anonymous: ~