vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        messages:
            upload_destination: oneup_flysystem.messages_filesystem
            directory_namer: App\Filesystem\MessageFilesystem
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: false
        wiki:
            upload_destination: oneup_flysystem.wiki_filesystem
        documents:
            upload_destination: oneup_flysystem.documents_filesystem
            directory_namer: App\Filesystem\DocumentFilesystem
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        student_absence:
            upload_destination: oneup_flysystem.student_absence_filesystem
            namer: Vich\UploaderBundle\Naming\UniqidNamer
