os: linux
dist: bionic
language: php

php:
  - '7.4'

services:
  - mysql

before_install:
  - php -i

stages:
  - test
  - build
  - release

cache: yarn

jobs:
  include:
    - stage: test
      language: php
      script:
        - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction
        - vendor/bin/phpstan analyze ./src --level 5 --memory-limit 1G
        - vendor/bin/phpunit --coverage-clover clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover clover.xml
    - stage: test
      language: node_js
      node_js: 10
      script:
        - yarn install
        - yarn encore production
    - stage: build
      language: python
      install:
        - pip install sphinx
        - pip install sphinx_rtd_theme
        - cd docs
        - make html
    - stage: build
      script:
        - nvm install 10
        - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction --no-dev
        - yarn install
        - yarn encore production
        - rm -rf node_modules
        - zip -r icc.zip
