language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

matrix:
  allow_failures:
    - php: '7.3'
    - php: nightly

services:
  - mysql

install:
  - composer install

script:
  - vendor/bin/phpstan analyze --level 5
  - vendor/bin/phpunit
