dist: xenial
language: php

php:
  - '7.2'
  - '7.3'
  - nightly

matrix:
  allow_failures:
    - php: '7.3'
    - php: nightly

services:
  - mysql

install:
  - composer install

script:
  - vendor/bin/phpstan analyze ./src --level 5
  - vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml