monolog:
    handlers:
        app:
            type: service
            id: App\Monolog\DatabaseHandler
            level: info
            channels: ["!request", "!php"]
        main:
            type: service
            id: App\Monolog\DatabaseHandler
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
