parameters:
    types_map:
        parent: parent
        teacher: teacher
        intern: intern
        student: student
        staff: staff
        facilitymanagement: staff
        secretary: staff
